# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(371, 496)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rezepteTable = QtWidgets.QTableWidget(self.centralWidget)
        self.rezepteTable.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.rezepteTable.setGridStyle(QtCore.Qt.SolidLine)
        self.rezepteTable.setObjectName("rezepteTable")
        self.rezepteTable.setColumnCount(3)
        self.rezepteTable.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.rezepteTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rezepteTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rezepteTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rezepteTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rezepteTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.rezepteTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rezepteTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rezepteTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.rezepteTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rezepteTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rezepteTable.setItem(1, 2, item)
        self.rezepteTable.horizontalHeader().setVisible(True)
        self.rezepteTable.horizontalHeader().setDefaultSectionSize(110)
        self.rezepteTable.horizontalHeader().setStretchLastSection(True)
        self.rezepteTable.verticalHeader().setVisible(False)
        self.rezepteTable.verticalHeader().setCascadingSectionResizes(False)
        self.gridLayout_2.addWidget(self.rezepteTable, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.newEntryButton = QtWidgets.QPushButton(self.centralWidget)
        self.newEntryButton.setObjectName("newEntryButton")
        self.horizontalLayout_2.addWidget(self.newEntryButton)
        self.saveButton = QtWidgets.QPushButton(self.centralWidget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_2.addWidget(self.saveButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 8, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 371, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuRezepte = QtWidgets.QMenu(self.menuBar)
        self.menuRezepte.setObjectName("menuRezepte")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuRezepte.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.rezepteTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.rezepteTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.rezepteTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Gericht:"))
        item = self.rezepteTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Zubereitungszeit(in M)"))
        item = self.rezepteTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Zubereitung"))
        __sortingEnabled = self.rezepteTable.isSortingEnabled()
        self.rezepteTable.setSortingEnabled(False)
        item = self.rezepteTable.item(0, 0)
        item.setText(_translate("MainWindow", "Spaghetti mit Soße"))
        item = self.rezepteTable.item(0, 1)
        item.setText(_translate("MainWindow", "15"))
        item = self.rezepteTable.item(0, 2)
        item.setText(_translate("MainWindow", "Nudel Kochen, Tomatensoße Kochen"))
        item = self.rezepteTable.item(1, 0)
        item.setText(_translate("MainWindow", "Lasagne"))
        item = self.rezepteTable.item(1, 1)
        item.setText(_translate("MainWindow", "35"))
        item = self.rezepteTable.item(1, 2)
        item.setText(_translate("MainWindow", "..."))
        self.rezepteTable.setSortingEnabled(__sortingEnabled)
        self.newEntryButton.setText(_translate("MainWindow", "Neues Rezept"))
        self.saveButton.setText(_translate("MainWindow", "Speichern"))
        self.menuRezepte.setTitle(_translate("MainWindow", "Rezepte:"))
